# Generated by Django 3.0.5 on 2021-03-31 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.TextField(choices=[('adding', 'Adding'), ('debiting', 'Debiting')], default='debiting', verbose_name='Transaction`s type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(max_length=255, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='summ',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Transaction`s name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Wallet', verbose_name='Wallet`s name'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Wallet`s name'),
        ),
    ]
